@baseUrl = http://localhost:3000/api/usuario/endereco
@token = token
@id = 1

### Cadastrar
POST {{baseUrl}}/cadastrar
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "apelido": "A casa do seu zé",
    "complemento": "Casa",
    "logradouro": "Rua do seu fulano",
    "numero": "123",
    "bairro": "Aquele Bairro",
    "cidade": "São-Paulo",
    "uf": "SP",
    "cep": "100000000"
}

### Modificar
PATCH {{baseUrl}}/modificar/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "apelido": "A casa do seu zé modificado",
    "complemento": "Casa",
    "logradouro": "Rua do seu fulano",
    "numero": "123",
    "bairro": "Aquele Bairro",
    "cidade": "São-Paulo",
    "uf": "SP",
    "cep": "100000000" 
}
