### Variáveis

@baseUrl = http://localhost:3000/api
@token = TOKEN_AQUI
### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "exemplo@email.com",
    "senha": "123",
}

### Cadastro
POST {{baseUrl}}/cadastrar
Content-Type: application/json

{
    "email": "exemplo@email.com",
    "senha": "123",
    "nome": "Exemplo da Silva",
    "telefone": "1599999999",
    "cpf": "12345678911237"
}

### ADMIN

### Cadastrar produto
POST {{baseUrl}}/produto/registrar
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "imagem": "teste.png",
    "nome": "Produto teste",
    "descricao": "Este é um teste",
    "preco": 1050,
    "categoria": 1,
    "estoque": 1
}

### Cadastrar categoria
POST {{baseUrl}}/produto/categoria/registrar
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "teste",
    "imagem": "teste.png"
}

### Modificar produto
PATCH {{baseUrl}}/produto/modificar
Content-Type: application/application/json
Authorization: Bearer {{token}}

{
    "id": 1,
    "imagem": "teste.png",
    "nome": "Produto teste modificado",
    "descricao": "Este é um teste",
    "preco": 1050,
    "categoria": 1,
    "estoque": 1
}

### Modificar categoria
PATCH {{baseUrl}}/produto/categoria/modificar
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id":,
    "nome":,
    "imagem":
}

### Listar produtos
GET {{baseUrl}}/produto/listar

### Listar usuários
GET {{baseUrl}}/listar
Authorization: Bearer {{token}}

### Deletar usuário
DELETE {{baseUrl}}/usuario/1
Authorization: Bearer {{token}}

### Restaurar Usuário
PATCH {{baseUrl}}/usuario/1/restaurar
Authorization: Bearer {{token}}
