### Variáveis

@baseUrl = http://localhost:3000/api/usuario
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGVyZmlsIjoiY2xpZW50ZSIsImlhdCI6MTc3NzE3MjM3OCwiZXhwIjoxNzc3MjU4Nzc4fQ.JV3W9g_tmBcAnfhZxcyKqljL9dECVIJuHCujfnOINo8
@id = 1

### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "exemplo@email.com",
    "senha": "123"
}



### Cadastro
POST {{baseUrl}}/cadastrar
Content-Type: application/json

{
    "email": "exemplo@email.com",
    "senha": "123",
    "nome": "Exemplo da Silva",
    "telefone": "1599999999",
    "cpf": "12345678911237"
}

### Modificar senha e/ou telefone
PATCH {{baseUrl}}/perfil
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "senha": "1234",
    "telefone": "1499999999"
}

### Deletar
DELETE {{baseUrl}}/desativar/{{id}}
Authorization: Bearer {{token}}

### Restaurar
PATCH {{baseUrl}}/restaurar/{{id}}
Authorization: Bearer {{token}}

### Listar 
GET {{baseUrl}}/listar
Authorization: Bearer {{token}}