### Variáveis

@baseUrl = http://localhost:3000/api/produto
@token = token
@id = 1

### Cadastrar
POST {{baseUrl}}/registrar
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "imagem": "teste.png",
    "nome": "Produto teste 2",
    "descricao": "Este é um teste",
    "preco": 1050,
    "categoria": 1,
    "estoque": 1
}

### Modificar
PATCH {{baseUrl}}/modificar/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "imagem": "teste.png",
    "nome": "Produto teste modificado 2",
    "descricao": "Este é um teste",
    "preco": 1050,
    "categoria": 1,
    "estoque": 1
}

### Deletar
DELETE {{baseUrl}}/desativar/{{id}}
Authorization: Bearer {{token}}

### Restaurar
PATCH {{baseUrl}}/restaurar/{{id}}
Authorization: Bearer {{token}}

### Listar PÚBLICO
GET {{baseUrl}}/listar

### Listar ADMIN ; Preciso achar um nome melhor
GET {{baseUrl}}/listar/todos
Authorization: Bearer {{token}}