### Variáveis

@baseUrl = http://localhost:3000/api/usuario
@token = token
@id = 4

### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "admin@admin",
    "senha": "admin"
}



### Cadastro
POST {{baseUrl}}/cadastrar
Content-Type: application/json

{
    "email": "exemplo2@email.com",
    "senha": "123",
    "nome": "Exemplo da Silva",
    "telefone": "1599999999",
    "cpf": "11345678911237"
}

### Modificar senha e/ou telefone
PATCH {{baseUrl}}/perfil
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "senha": "123"
}

### Deletar
DELETE {{baseUrl}}/desativar/{{id}}
Authorization: Bearer {{token}}

### Restaurar
PATCH {{baseUrl}}/restaurar/{{id}}
Authorization: Bearer {{token}}

### Listar 
GET {{baseUrl}}/listar
Authorization: Bearer {{token}}