### Variáveis

@baseUrl = http://localhost:3000/api/categoria
@token = token
@id = 1

### Cadastrar 
POST {{baseUrl}}/registrar
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Outra categoria2",
    "imagem": "teste2.png"
}

### Modificar
PATCH {{baseUrl}}/modificar/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "coisas",
    "imagem": "testeimagem.png"
}

### Deletar
DELETE {{baseUrl}}/deletar/{{id}}
Authorization: Bearer {{token}}

### Restaurar
DELETE {{baseUrl}}/deletar/{{id}}
Authorization: Bearer {{token}}

### Listar
GET {{baseUrl}}/listar

### Listar todas
GET {{baseUrl}}/listar/todas
Authorization: Bearer {{token}}