@baseUrl = http://localhost:3000/api
@id = 1

# @name login
POST {{baseUrl}}/usuario/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

###
@token = {{login.response.body.token}}

### Lista de todas as categorias
GET {{baseUrl}}/admin/categoria/
Authorization: Bearer {{token}}

### Registrar categoria
POST {{baseUrl}}/admin/categoria/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"example category"
}

### Adicionando imagem
PATCH {{baseUrl}}/admin/categoria/{{id}}/imagem
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< ./image.jpg
------WebKitFormBoundary--

### Deletar categoria
DELETE  {{baseUrl}}/admin/categoria/{{id}}
Authorization: Bearer {{token}}

### Restaurar categoria
PATCH   {{baseUrl}}/admin/categoria/restaurar/{{id}}
Authorization: Bearer {{token}}

### Modificar categoria
PATCH {{baseUrl}}/admin/categoria/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"example"
}