@baseUrl = http://localhost:3000/api
@id = 2

# @name login
POST {{baseUrl}}/usuario/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

###
@token = {{login.response.body.token}}

### Lista de todos os produtos.
GET {{baseUrl}}/admin/produto/
Authorization: Bearer {{token}}

### Registrar produto
POST {{baseUrl}}/admin/produto/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"example",
    "description":"example",
    "price":"1",
    "category":"1",
    "stock":"1"  
}

### Adicionando imagem
PATCH {{baseUrl}}/admin/produto/{{id}}/imagem
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< ./image.jpg
------WebKitFormBoundary--

### Deletar produto
DELETE {{baseUrl}}/admin/produto/{{id}}
Authorization: Bearer {{token}}

### Restaurar produto
PATCH {{baseUrl}}/admin/produto/restaurar/{{id}}
Authorization: Bearer {{token}}

### Modificar produto
PATCH {{baseUrl}}/admin/produto/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"exampl3",
    "description":"exampl3",
    "price":"1",
    "category":"1",
    "stock":"2"  
}
