@baseUrl = http://localhost:3000/api

### Solicitar recuperação
POST {{baseUrl}}/senha/recuperar
Content-Type: application/json

{
  "email": "johndoe@email.com"
}

### Redefinir senha (token vem do email)
POST {{baseUrl}}/senha/redefinir
Content-Type: application/json

{
  "token": "token",
  "new_password": "wordpass"
}